sonar.projectKey=AnaPLysyk_INTELLIGENCE
sonar.projectName=INTELLIGENCE
sonar.organization=anaplysyk
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.sources=pom,utils,config,cucumber,scripts
sonar.tests=steps
sonar.test.inclusions=steps/**/*.steps.ts
sonar.exclusions=**/node_modules/**,**/.cucumber-dist/**,**/test-results/**,**/reports/**,**/test-data/generated/**,**/*.json,**/*.png,**/*.jpg
sonar.coverage.exclusions=pom/**,utils/**,config/**,cucumber/**,scripts/**,steps/**
sonar.cpd.exclusions=steps/**,utils/data/**
