sonar.projectKey=AnaPLysyk_INTELLIGENCE
sonar.projectName=INTELLIGENCE
sonar.organization=anaplysyk
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.sources=support
sonar.tests=tests
sonar.test.inclusions=tests/**/*.spec.ts,tests/**/*.test.ts
sonar.exclusions=**/node_modules/**,**/test-results/**,**/playwright-report/**,**/dist/**,**/coverage/**,**/*.json,**/*.png,**/*.jpg
sonar.coverage.exclusions=support/**,tests/**
sonar.cpd.exclusions=tests/**,support/**/fixtures/**,support/**/massas/**
